Change startupProbe path
Seeing `Startup probe failed: HTTP probe failed with statuscode: 503` in SBOX Jenkins pod logs, timeout period seems fine but also seeing:

```
WARNING: Exception thrown during refresh
java.util.concurrent.CompletionException: org.springframework.security.access.AccessDeniedException: Please login to access job HMCTS_Sandbox_CDM
```

In the pod logs, meaning the '/login' default path could be causing the 503.